[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Syndesi"
authors = [{name = "SÃ©bastien", email = "sebastien.deriaz1@gmail.com"}]
dynamic = ["version", "description"]
